# Generated by Django 3.1.4 on 2022-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platerak', '0002_platerak_delete_platera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platerak',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
